"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import { Providers } from '@/redux/provider';
import Layout from "@/components/Layout";
import { usePathname } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const pathname = usePathname();
  console.log(pathname);
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {
            pathname !== '/' ?
              <Layout>
                {children}
              </Layout>
              :
              <>
                {children}
              </>
          }
        </Providers>
      </body>
    </html>
  )
}
