import './globals.css'
import { Inter } from 'next/font/google'
import SnackBar from '@/components/SnackBarComponent';
import { Providers } from '@/redux/provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          {children}
          <SnackBar />
        </Providers>
      </body>
    </html>
  )
}
